[theme]
base = "dark"
primaryColor = "#f4f5f7"
backgroundColor = "#08080a"
secondaryBackgroundColor = "#0e0e12"
textColor = "#f4f5f7"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
