[theme]
base = "light"
primaryColor = "#0a0a0a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f6f7"
textColor = "#0a0a0a"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
